import { Router} from 'express'
import z from 'zod'
import { getToken } from './token.route.ts'
import type { TokenResponse } from '../storage.ts'
import axios from 'axios'
import type { SpotifySearchQueryResponse, TrackResponseWrapper } from '../types/SpotifyInnerApi.ts'
import pLimit from 'p-limit'
import { isArtistMatch, isTitleMatch } from '../utils/spotify-text.js'
import type { PlaylistStatus } from '../types/types.ts'

export const spotifyRouter = Router()

const userToPlaylistMap = new Map<string, PlaylistStatus>()

const hashes = {
   addToPlaylist: '47b2a1234b17748d332dd0431534f22450e9ecbb3d5ddcdacbd83368636a0990',
   fetchPlaylist: 'a65e12194ed5fc443a1cdebed5fabe33ca5b07b987185d63c72483867ad13cb4',
   searchTopResultsList: '12d940b3f7381506a82ff5382eb59b0ed65118656e6bcdfbe4cebc528f75d29d',
} as const

const headers = {
   'User-Agent':
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36',
   // 'Spotify-App-Version': '1.2.84.177.g11e44b3e', // fallback
   Origin: 'https://open.spotify.com',
   Referer: 'https://open.spotify.com/',
   'Sec-Ch-Ua': '"Not(A:Brand";v="8", "Chromium";v="144", "Google Chrome";v="144"',
   'Sec-Ch-Ua-Mobile': '?0',
   'Sec-Ch-Ua-Platform': '"Windows"',
   'App-Platform': 'WebPlayer',
   Accept: 'application/json',
   'Content-Type': 'application/json;charset=UTF-8',
   'accept-language': 'en',
} as const

const buildHeaders = async (t: TokenResponse) => {
   return {
      ...headers,
      Authorization: `Bearer ${t.access.accessToken}`,
      'Client-Token': t.client.token,
      'Spotify-App-Version': t.client.version,
   }
}

async function fetchInnerGraphApi<T extends Record<string, any>>({
   token,
   operationName,
   variables,
   hash,
}: {
   token: TokenResponse
   operationName: string
   variables: Record<string, any>
   hash: string
}) {
   const { data } = await axios.post<{ data: T }>(
      'https://api-partner.spotify.com/pathfinder/v2/query',
      {
         variables,
         operationName,
         extensions: {
            persistedQuery: {
               version: 1,
               sha256Hash: hash,
            },
         },
      },
      {
         headers: await buildHeaders(token),
      },
   )
   if (data?.data) {
      const key = Object.keys(data.data)[0]
      const value = data.data[key as keyof typeof data.data]
      if ('__typename' in value && value.__typename === 'GenericError') {
         throw new Error(
            JSON.stringify({
               ...data.data,
               operationName,
               variables,
            }),
         )
      }
   }
   return data.data
}

spotifyRouter.use(async (req, res, next) => {
   const token = await getToken()
   if (!token) return res.status(500).json({ message: 'Failed to obtain token' })
   res.locals.token = token
   next()
})

spotifyRouter.post('/spotify/playlist', async (req, res) => {
   const regenerate = false // TODO implement regenerate
   const validationRes = z.object({ 'x-client-id': z.string() }).safeParse(req.headers)

   if (!validationRes.success) {
      return res.status(400).json({ message: 'Validation failed', details: z.treeifyError(validationRes.error) })
   }
   const clientId = validationRes.data['x-client-id']
   const token = res.locals.token as TokenResponse

   if (!regenerate && userToPlaylistMap.has(clientId)) {
      return res.json({ id: userToPlaylistMap.get(clientId) })
   } else {
      // create a new playlist
      const customHeaders = {
         ...(await buildHeaders(token)),
         Accept: 'application/json',
      }
      const { data } = await axios.post<{ uri: string; revision: string }>(
         'https://spclient.wg.spotify.com/playlist/v2/playlist',
         {
            ops: [
               {
                  kind: 'UPDATE_LIST_ATTRIBUTES',
                  updateListAttributes: {
                     newAttributes: {
                        values: {
                           name: 'osu to spotify',
                           description: 'Generated by osu.yageey.me at ' + new Date().toLocaleDateString(),
                        },
                     },
                  },
               },
            ],
         },
         { headers: customHeaders },
      )

      await axios.post(
         'https://spclient.wg.spotify.com/playlist/v2/user/313ylfw2p3xrcb5nsyubpkcxs4t4/rootlist/changes',
         {
            deltas: [
               {
                  ops: [
                     {
                        kind: 'ADD',
                        add: {
                           addFirst: true,
                           items: [
                              {
                                 uri: data.uri,
                                 attributes: { timestamp: Date.now().toString() },
                              },
                           ],
                        },
                     },
                  ],
                  info: { source: { client: 'WEBPLAYER' } },
               },
            ],
         },
         { headers: customHeaders },
      )

      const id = data.uri.split(':').pop()
      if (!id)
         return res.status(500).json({ message: 'Something went wrong wile creating playlist. No ID from full uri: ' + data.uri })
      userToPlaylistMap.set(clientId, { playlistId: id, status: 'ready' })
      res.json({ id })
   }
})

spotifyRouter.post('/spotify/playlist/:playlistId/upload-beatmaps', async (req, res) => {
   // FIXME setup Nginx too
   // TODO s:
   // check if everything existed, add in DB map for map id to spotify track id, and check if the map is already in the playlist before adding it again
   // make TIMEOUT_MS dynamic based on the number of beatmaps
   // test concurrency
   // роз'єднати browser logs and server logs шоб записувались в окремі файли
   // додати db щоб все було persistance
   const TIMEOUT_MS = 20 * 60 * 100
   req.setTimeout(TIMEOUT_MS)
   res.setTimeout(TIMEOUT_MS)
   const limit = pLimit(1)

   // validation
   const validationRes = z
      .object({
         headers: z.object({ 'x-client-id': z.string() }),
         params: z.object({ playlistId: z.string() }),
         beatmaps: z.array(
            z.object({
               Title: z.string().nullish(),
               TitleUnicode: z.string().nullish(),
               Artist: z.string().nullish(),
               ArtistUnicode: z.string().nullish(),
            }),
         ),
      })
      .safeParse({
         headers: req.headers,
         params: req.params,
         beatmaps: req.body,
      })
   if (!validationRes.success) {
      return res.status(400).json({ message: 'Validation failed', details: z.treeifyError(validationRes.error) })
   }
   const { headers, params, beatmaps } = validationRes.data
   const clientId = headers['x-client-id']

   const token = res.locals.token as TokenResponse
   const readyPl = userToPlaylistMap.get(clientId)
   if (!readyPl || readyPl?.playlistId !== params.playlistId || readyPl?.status !== 'ready') {
      return res.status(403).json({ message: 'Invalid playlistId for the given clientId' })
   }
   const processingPl: PlaylistStatus = {
      playlistId: readyPl.playlistId,
      status: 'processing',
      total: beatmaps.length,
      notFound: 0,
      processed: 0,
      found: 0,
      errored: 0,
   }
   userToPlaylistMap.set(clientId, processingPl)

   // search for tracks
   const tracksUris: string[] = []
   const searchTasks = beatmaps.map((beatmap) =>
      limit(async () => {
         const query = `${beatmap.ArtistUnicode || beatmap.Artist || ''} ${beatmap.TitleUnicode || beatmap.Title || ''}`.trim()

         try {
            const data = await fetchInnerGraphApi<SpotifySearchQueryResponse>({
               token,
               operationName: 'searchTopResultsList',
               hash: hashes.searchTopResultsList,
               variables: {
                  includeAlbumPreReleases: false,
                  includeArtistHasConcertsField: true,
                  includeAudiobooks: false,
                  includeAuthors: false,
                  includeEpisodeContentRatingsV2: true,
                  includePreReleases: true,
                  isPrefix: null,
                  limit: 5,
                  numberOfTopResults: 5,
                  offset: 0,
                  query,
                  sectionFilters: ['GENERIC', 'VIDEO_CONTENT'],
               },
            })

            const items = data?.searchV2?.topResultsV2?.itemsV2 ?? []
            const tracks = items.filter(
               (i): i is { item: TrackResponseWrapper; matchedFields?: string[] } => i.item.__typename === 'TrackResponseWrapper',
            )

            // filtering tracks to find real match instead of recommendations
            let selectedTrack: TrackResponseWrapper | null = null
            for (const track of tracks) {
               const titleMatched =
                  isTitleMatch(beatmap.TitleUnicode, track.item.data.name) || isTitleMatch(beatmap.Title, track.item.data.name)

               const artistMatched = track.item.data.artists.items.some(
                  (artist) =>
                     isArtistMatch(beatmap.ArtistUnicode, artist.profile.name) ||
                     isArtistMatch(beatmap.Artist, artist.profile.name),
               )

               // TODO mark as low confidence
               // if only title or only artist matched, and not both
               // if 100% match
               // if substring match
               if (titleMatched || artistMatched) {
                  selectedTrack = track.item
                  break
               }
            }

            const uri = selectedTrack?.data.uri
            if (uri) {
               processingPl.found++
               tracksUris.push(uri)
            } else {
               processingPl.notFound++
            }
         } catch (err) {
            console.error('Error searching for beatmap:', query, err)
            processingPl.errored++
         } finally {
            processingPl.processed++
         }
      }),
   )
   await Promise.all(searchTasks)

   if (tracksUris.length === 0) {
      Object.assign(processingPl, {
         status: 'error',
         message: 'Nothing found for the given beatmaps',
      })
      return res.status(404).json(processingPl)
   }

   // add beatmaps to the playlist
   try {
      await fetchInnerGraphApi({
         hash: hashes.addToPlaylist,
         operationName: 'addToPlaylist',
         token,
         variables: {
            newPosition: {
               fromUid: null,
               moveType: 'BOTTOM_OF_PLAYLIST',
            },
            playlistItemUris: tracksUris,
            playlistUri: `spotify:playlist:${params.playlistId}`,
         },
      })
   } catch (error) {
      Object.assign(processingPl, {
         status: 'error',
         message: 'Failed to add tracks to playlist',
      })
      return res.status(500).json(processingPl)
   }

   processingPl.status = 'filled'
   res.status(200).json(processingPl)
})

spotifyRouter.get('/spotify/playlist', async (req, res) => {
   const validationRes = z.object({ 'x-client-id': z.string() }).safeParse(req.headers)
   if (!validationRes.success) {
      return res.status(400).json({ message: 'Validation failed', details: z.treeifyError(validationRes.error) })
   }
   const clientId = validationRes.data['x-client-id']
   if (!userToPlaylistMap.has(clientId)) {
      return res.status(404).json({ message: 'No playlist found for the given clientId' })
   }

   const playlistStatus = userToPlaylistMap.get(clientId)!
   res.json(playlistStatus)
})
